export type TextFontOption = { label: string; value: string };

export const TEXT_FONT_OPTIONS: TextFontOption[] = [
  { label: "Abril Fatface", value: "Abril Fatface" },
  { label: "Amatic SC", value: "Amatic SC" },
  { label: "Archivo", value: "Archivo" },
  { label: "Arimo", value: "Arimo" },
  { label: "Arvo", value: "Arvo" },
  { label: "Average", value: "Average" },
  { label: "Barlow", value: "Barlow" },
  { label: "Bebas Neue", value: "Bebas Neue" },
  { label: "Birthstone", value: "Birthstone" },
  { label: "Bitter", value: "Bitter" },
  { label: "Bree Serif", value: "Bree Serif" },
  { label: "Cabin", value: "Cabin" },
  { label: "Cardo", value: "Cardo" },
  { label: "Caveat", value: "Caveat" },
  { label: "Cinzel", value: "Cinzel" },
  { label: "Cormorant Garamond", value: "Cormorant Garamond" },
  { label: "Crimson Text", value: "Crimson Text" },
  { label: "DM Sans", value: "DM Sans" },
  { label: "EB Garamond", value: "EB Garamond" },
  { label: "Fanwood Text", value: "Fanwood Text" },
  { label: "Fira Sans", value: "Fira Sans" },
  { label: "Fjalla One", value: "Fjalla One" },
  { label: "Inter", value: "Inter" },
  { label: "Josefin Sans", value: "Josefin Sans" },
  { label: "Josefin Slab", value: "Josefin Slab" },
  { label: "Karla", value: "Karla" },
  { label: "Lato", value: "Lato" },
  { label: "Libre Baskerville", value: "Libre Baskerville" },
  { label: "Lora", value: "Lora" },
  { label: "Lustria", value: "Lustria" },
  { label: "Merriweather", value: "Merriweather" },
  { label: "Montserrat", value: "Montserrat" },
  { label: "Noto Sans", value: "Noto Sans" },
  { label: "Nunito", value: "Nunito" },
  { label: "Old Standard TT", value: "Old Standard TT" },
  { label: "Open Sans", value: "Open Sans" },
  { label: "Oswald", value: "Oswald" },
  { label: "PT Sans", value: "PT Sans" },
  { label: "Pacifico", value: "Pacifico" },
  { label: "Pinyon Script", value: "Pinyon Script" },
  { label: "Playfair Display", value: "Playfair Display" },
  { label: "Poppins", value: "Poppins" },
  { label: "Praise", value: "Praise" },
  { label: "Proza Libre", value: "Proza Libre" },
  { label: "Quattrocento", value: "Quattrocento" },
  { label: "Quattrocento Sans", value: "Quattrocento Sans" },
  { label: "Raleway", value: "Raleway" },
  { label: "Roboto", value: "Roboto" },
  { label: "Roboto Slab", value: "Roboto Slab" },
  { label: "Rubik", value: "Rubik" },
  { label: "Source Sans 3", value: "Source Sans 3" },
  { label: "Syne", value: "Syne" },
  { label: "Teko", value: "Teko" },
  { label: "Ubuntu", value: "Ubuntu" },
  { label: "Allura", value: "Allura" },
  { label: "DM Serif Display", value: "DM Serif Display" },
  { label: "Fraunces", value: "Fraunces" },
  { label: "Great Vibes", value: "Great Vibes" },
  { label: "Handlee", value: "Handlee" },
  { label: "Italianno", value: "Italianno" },
  { label: "Parisienne", value: "Parisienne" },
  { label: "Patrick Hand", value: "Patrick Hand" },
  { label: "Sacramento", value: "Sacramento" },
  { label: "Satisfy", value: "Satisfy" },
  { label: "Yeseva One", value: "Yeseva One" },
];
