// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dev/library-thumbnail-preview" | "/editor" | "/editor-v2" | "/editor-v2/design-system" | "/editor-v2/designs/[storageId]" | "/editor-v2/new" | "/editor/design-system" | "/editor/designs/[storageId]" | "/editor/new" | "/library" | "/sign-in/[[...sign-in]]"
type AppRouteHandlerRoutes = "/api/editor-v2/designs" | "/api/editor-v2/designs/[id]" | "/api/editor-v2/designs/[id]/versions" | "/api/editor-v2/designs/[id]/versions/[versionId]" | "/api/editor-v2/icon-library" | "/api/image-proxy" | "/api/internal/blob-gc" | "/api/upload-trace" | "/api/upload-trace/complete" | "/api/wip" | "/api/wip/[id]" | "/api/wip/[id]/versions" | "/api/wip/[id]/versions/[versionId]"
type PageRoutes = never
type LayoutRoutes = "/" | "/editor" | "/editor-v2"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/editor-v2/designs": {}
  "/api/editor-v2/designs/[id]": { "id": string; }
  "/api/editor-v2/designs/[id]/versions": { "id": string; }
  "/api/editor-v2/designs/[id]/versions/[versionId]": { "id": string; "versionId": string; }
  "/api/editor-v2/icon-library": {}
  "/api/image-proxy": {}
  "/api/internal/blob-gc": {}
  "/api/upload-trace": {}
  "/api/upload-trace/complete": {}
  "/api/wip": {}
  "/api/wip/[id]": { "id": string; }
  "/api/wip/[id]/versions": { "id": string; }
  "/api/wip/[id]/versions/[versionId]": { "id": string; "versionId": string; }
  "/dev/library-thumbnail-preview": {}
  "/editor": {}
  "/editor-v2": {}
  "/editor-v2/design-system": {}
  "/editor-v2/designs/[storageId]": { "storageId": string; }
  "/editor-v2/new": {}
  "/editor/design-system": {}
  "/editor/designs/[storageId]": { "storageId": string; }
  "/editor/new": {}
  "/library": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/editor": never
  "/editor-v2": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
