// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/dev/library-thumbnail-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/library-thumbnail-preview">> = Specific
  const handler = {} as typeof import("../../../app/dev/library-thumbnail-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor-v2/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor-v2/design-system">> = Specific
  const handler = {} as typeof import("../../../app/editor-v2/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor-v2/designs/[storageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor-v2/designs/[storageId]">> = Specific
  const handler = {} as typeof import("../../../app/editor-v2/designs/[storageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor-v2/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor-v2/new">> = Specific
  const handler = {} as typeof import("../../../app/editor-v2/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor-v2">> = Specific
  const handler = {} as typeof import("../../../app/editor-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor/design-system">> = Specific
  const handler = {} as typeof import("../../../app/editor/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor/designs/[storageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor/designs/[storageId]">> = Specific
  const handler = {} as typeof import("../../../app/editor/designs/[storageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor/new">> = Specific
  const handler = {} as typeof import("../../../app/editor/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor">> = Specific
  const handler = {} as typeof import("../../../app/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../../app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../../app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/editor-v2/designs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editor-v2/designs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/editor-v2/designs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/editor-v2/designs/[id]/versions/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editor-v2/designs/[id]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../../app/api/editor-v2/designs/[id]/versions/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/editor-v2/designs/[id]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editor-v2/designs/[id]/versions">> = Specific
  const handler = {} as typeof import("../../../app/api/editor-v2/designs/[id]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/editor-v2/designs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editor-v2/designs">> = Specific
  const handler = {} as typeof import("../../../app/api/editor-v2/designs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/editor-v2/icon-library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editor-v2/icon-library">> = Specific
  const handler = {} as typeof import("../../../app/api/editor-v2/icon-library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/image-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/image-proxy">> = Specific
  const handler = {} as typeof import("../../../app/api/image-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/internal/blob-gc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/blob-gc">> = Specific
  const handler = {} as typeof import("../../../app/api/internal/blob-gc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload-trace/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload-trace/complete">> = Specific
  const handler = {} as typeof import("../../../app/api/upload-trace/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload-trace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload-trace">> = Specific
  const handler = {} as typeof import("../../../app/api/upload-trace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wip/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wip/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/wip/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wip/[id]/versions/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wip/[id]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../../app/api/wip/[id]/versions/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wip/[id]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wip/[id]/versions">> = Specific
  const handler = {} as typeof import("../../../app/api/wip/[id]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wip">> = Specific
  const handler = {} as typeof import("../../../app/api/wip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/editor-v2/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/editor-v2">> = Specific
  const handler = {} as typeof import("../../../app/editor-v2/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/editor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/editor">> = Specific
  const handler = {} as typeof import("../../../app/editor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
